# Generated by Django 5.1.4 on 2024-12-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="number",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="profile",
            name="summary",
            field=models.TextField(max_length=500),
        ),
    ]
