# Generated by Django 5.1.4 on 2024-12-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0002_alter_profile_number_alter_profile_summary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
